### ISSUE TITLE
Cannot remove files created by IndexedChronicle on Windows 7 (32-bit JVMs only)

### ISSUE THREAD

**Issue by rwicke** [peter-lawrey/Java-Chronicle#19]
On my Windows 7 box I have run into an issue with Chronicle 1.6 where I cannot remove the data/index files created by an IndexedChronicle even after I have closed it. I only get this issue on 32-bit versions of Java 6 or Java 7. 64-bit versions are fine. I have also tested on Linux and do not get any problems there. I realise that it's probably more a JVM then a code issue but, oddly, everything works fine with an earlier version of Chronicle (1.3, I believe).

When I look at the JVM process in procexp on Windows I can see that the process no longer has file handles for the data/index files after calling close(). On 32-bit JVMs it does, however, have DLL handles to them. Weird.

The following code below reproduces the problem.

``` java
import java.io.File;

import com.higherfrequencytrading.chronicle.Excerpt;
import com.higherfrequencytrading.chronicle.impl.IndexedChronicle;


public class TestChronicleFileRemove {

    public static void main(String[] args) throws Exception {
        String basePath = args[0];
        boolean useUnsafe = args.length > 1 ? Boolean.parseBoolean(args[1]) : false;
        IndexedChronicle chronicle = new IndexedChronicle(args[0], 16);
        chronicle.useUnsafe(useUnsafe);
        Excerpt excerpt = chronicle.createExcerpt();
        excerpt.startExcerpt(32);
        excerpt.writeChars("Hello");
        excerpt.finish();
        excerpt.close();
        chronicle.close();

        removeFile(basePath + ".data");
        removeFile(basePath + ".index");

    }

    private static void removeFile(String path) {
        if (new File(path).delete()) {
            System.out.println("removed: " + path);
        } else {
            System.out.println("could not remove: " + path);
        }
    }

}
```

**Comment by peter-lawrey** [comment]
Resource management has significantly improved in the x.20 releases and should resolve this issue.
